# Generated by Django 4.1.5 on 2023-01-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllServices',
            fields=[
                ('slID', models.AutoField(primary_key=True, serialize=False)),
                ('selectImage', models.ImageField(upload_to='AllServicesDBimgFolder')),
                ('name', models.CharField(max_length=122)),
                ('homepagecatagori', models.CharField(blank=True, max_length=50, null=True)),
                ('Offer', models.IntegerField()),
                ('silverPrice', models.IntegerField()),
                ('silverLeads', models.IntegerField()),
                ('silverDay', models.IntegerField()),
                ('goldPrice', models.IntegerField()),
                ('goldLeads', models.IntegerField()),
                ('goldDay', models.IntegerField()),
                ('diamondPrice', models.IntegerField()),
                ('diamondLeads', models.IntegerField()),
                ('diamondDay', models.IntegerField()),
                ('desc', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClickHistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectImage', models.URLField()),
                ('slID', models.IntegerField()),
                ('name', models.CharField(max_length=122)),
                ('totalClick', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('dateee', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ControlWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VarName', models.CharField(max_length=122)),
                ('charecterVar', models.CharField(blank=True, max_length=122, null=True)),
                ('integetVar', models.IntegerField(blank=True, null=True)),
                ('emailVar', models.EmailField(blank=True, max_length=254, null=True)),
                ('textVar', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FreeTrialRequest',
            fields=[
                ('slID', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FreeTrialUnderReview',
            fields=[
                ('slID', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=254)),
                ('linkedIn_Profile', models.URLField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FreeTrialUser',
            fields=[
                ('slID', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=254)),
                ('freeTrialStatus', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('slID', models.AutoField(primary_key=True, serialize=False)),
                ('selectFile', models.FileField(blank=True, null=True, upload_to='FileDBFolder')),
                ('fullname', models.CharField(max_length=122)),
                ('trakingLink', models.URLField(blank=True, default='')),
                ('paymentLink', models.URLField(blank=True, default='')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('totalprice', models.IntegerField(blank=True, null=True)),
                ('countryoption', models.CharField(max_length=100)),
                ('servicesOption', models.CharField(max_length=50)),
                ('enterbuget', models.IntegerField(blank=True, null=True)),
                ('numberofleads', models.IntegerField(blank=True, null=True)),
                ('requirmentdesc', models.TextField(blank=True, null=True)),
                ('productID', models.IntegerField()),
                ('onlyCountryCode', models.CharField(max_length=20)),
                ('otp', models.IntegerField()),
                ('otpStatus', models.CharField(max_length=50)),
                ('orderStatus', models.CharField(max_length=70)),
                ('orderCoplition', models.IntegerField()),
                ('peymentStatus', models.CharField(max_length=50)),
                ('productLink', models.URLField(blank=True, default='')),
                ('expectedDeliveryDate', models.DateField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerDayOrderPerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('orderNo', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('slID', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('totalOrder', models.IntegerField(default=1)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
