# Generated by Django 4.1.5 on 2023-01-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goobusinessesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyUsDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=50, null=True)),
                ('Subtitle', models.CharField(blank=True, max_length=254, null=True)),
                ('ImagePic', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
