# Generated by Django 4.1.5 on 2023-01-31 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goobusinessesapp', '0002_whyusdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='totalSpent',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='whyusdb',
            name='imageHeight',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='whyusdb',
            name='imageWidth',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
