# Generated by Django 4.1.5 on 2023-01-31 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goobusinessesapp', '0003_userdetails_totalspent_whyusdb_imageheight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='date',
            new_name='joiningdate',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='lastOrderdate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='totalPaymentReceived',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='totalSpent',
            field=models.IntegerField(default=0),
        ),
    ]
