# Generated by Django 4.1.5 on 2023-01-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goobusinessesapp', '0004_rename_date_userdetails_joiningdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=50, null=True)),
                ('Subtitle', models.CharField(blank=True, max_length=254, null=True)),
                ('ImagePic', models.ImageField(blank=True, null=True, upload_to='')),
                ('imageWidth', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('imageHeight', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
