# Generated by Django 4.1.5 on 2023-01-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goobusinessesapp', '0006_rename_selectimage_clickhistry_productlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlweb',
            name='datetimeVar',
            field=models.DateField(blank=True, null=True),
        ),
    ]
