# Generated by Django 4.1.5 on 2023-02-05 23:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goobusinessesapp', '0009_remove_emailseendb_unicnum_emailseendb_lastseentime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='odrTime',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
