# Generated by Django 4.1.5 on 2023-02-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goobusinessesapp', '0010_orderlist_odrtime_alter_orderlist_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraImageorFileDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=50, null=True)),
                ('selectFile', models.FileField(upload_to='ExtraImageorFileDBDBFolder')),
                ('upTime', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
