# Generated by Django 4.1.5 on 2023-02-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goobusinessesapp', '0011_extraimageorfiledb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraImageDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=50, null=True)),
                ('selectImage', models.ImageField(upload_to='ExtraImageDBFolder')),
                ('upTime', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ExtraImageorFileDB',
        ),
    ]
