# Generated by Django 4.1.7 on 2023-02-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goobusinessesapp', '0014_openviaemail_alter_orderlist_jobdownload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('openType', models.CharField(max_length=100)),
                ('openNo', models.IntegerField()),
                ('opnmessage', models.CharField(max_length=120)),
                ('lastTime', models.TimeField(auto_now=True)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
