# Generated by Django 4.1.7 on 2023-02-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goobusinessesapp', '0016_clickhistry_timee_clickhistry_userauthdt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickHistryByUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAuthDt', models.EmailField(max_length=254)),
                ('productLink', models.URLField()),
                ('slID', models.IntegerField()),
                ('name', models.CharField(max_length=122)),
                ('totalClick', models.IntegerField()),
                ('timee', models.TimeField(auto_now=True)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='clickhistry',
            name='userAuthDt',
        ),
    ]
