# Generated by Django 4.1.7 on 2023-02-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goobusinessesapp', '0018_alter_clickhistrybyuser_userauthdt'),
    ]

    operations = [
        migrations.AddField(
            model_name='allservices',
            name='slag',
            field=models.SlugField(default='best'),
        ),
    ]
