# Generated by Django 4.1.7 on 2023-02-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goobusinessesapp', '0020_subscribelist_unsubscribelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribelist',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='unsubscribelist',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
