# Generated by Django 4.1.7 on 2023-03-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goobusinessesapp', '0021_subscribelist_count_unsubscribelist_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutdb',
            name='ImagePic',
            field=models.ImageField(blank=True, null=True, upload_to='AboutDBFolder'),
        ),
        migrations.AlterField(
            model_name='allservices',
            name='diamondLeads',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='allservices',
            name='goldLeads',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='allservices',
            name='silverLeads',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='whyusdb',
            name='ImagePic',
            field=models.ImageField(blank=True, null=True, upload_to='WhyDBFolder'),
        ),
    ]
