# Generated by Django 5.0 on 2024-01-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goobusinessesapp', '0023_internuserdetails_registationformdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllInternBatchs',
            fields=[
                ('slID', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeID', models.CharField(max_length=40)),
                ('batchName', models.CharField(max_length=30)),
                ('fullname', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('ChooseJobOrInternship', models.CharField(max_length=50)),
                ('ChooseFieldOfInterest', models.CharField(max_length=50)),
                ('HighestQualification', models.CharField(max_length=50)),
                ('CollegeName', models.CharField(max_length=100)),
                ('MajorFieldOfStudy', models.CharField(max_length=50)),
                ('YearOfGraduation', models.IntegerField(blank=True, null=True)),
                ('WorkExperienceIfAny', models.TextField(blank=True, null=True)),
                ('GitHubProfile', models.URLField(blank=True, default='')),
                ('LinkedInProfile', models.URLField(blank=True, default='')),
                ('address', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
                ('countryCode', models.CharField(max_length=6)),
                ('pinCode', models.CharField(max_length=6)),
                ('payment', models.BooleanField(default=False)),
                ('paymentStatus', models.CharField(blank=True, max_length=30, null=True)),
                ('paymentAmount', models.IntegerField(blank=True, default=0, null=True)),
                ('projectGitHubLinkCount', models.IntegerField(blank=True, default=0, null=True)),
                ('liveLinkCount', models.IntegerField(blank=True, default=0, null=True)),
                ('totalMassage', models.IntegerField(blank=True, default=0, null=True)),
                ('confidenceMarks', models.IntegerField(blank=True, default=0, null=True)),
                ('codingMarks', models.IntegerField(blank=True, default=0, null=True)),
                ('outputMarks', models.IntegerField(blank=True, default=0, null=True)),
                ('onTimeSubmitMarks', models.IntegerField(blank=True, default=0, null=True)),
                ('remark', models.CharField(max_length=30)),
                ('acceptTime', models.TimeField(auto_now_add=True)),
                ('acceptdate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BatchesInstractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchName', models.CharField(max_length=50)),
                ('Instractions', models.TextField(blank=True, null=True)),
                ('lastUpdate', models.DateField(auto_now=True)),
                ('startDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
