# Generated by Django 5.0 on 2024-01-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goobusinessesapp', '0024_allinternbatchs_batchesinstractions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallingConverssionTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slID', models.IntegerField(blank=True, default=0, null=True)),
                ('EmployeeID', models.CharField(max_length=40)),
                ('batchName', models.CharField(max_length=30)),
                ('fullname', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('payment', models.BooleanField(default=False)),
                ('paymentStatus', models.CharField(blank=True, max_length=30, null=True)),
                ('paymentAmount', models.IntegerField(blank=True, default=0, null=True)),
                ('lastUpdateTime', models.TimeField(auto_now=True)),
                ('lastUpdatedate', models.DateField(auto_now=True)),
                ('acceptTime', models.TimeField(auto_now_add=True)),
                ('acceptdate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
