# Generated by Django 5.0 on 2024-03-04 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goobusinessesapp', '0027_allinternbatchs_acceptallagriment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutDB',
        ),
        migrations.DeleteModel(
            name='AllInternBatchs',
        ),
        migrations.DeleteModel(
            name='BatchesInstractions',
        ),
        migrations.DeleteModel(
            name='CallingConverssionTrack',
        ),
        migrations.DeleteModel(
            name='ClickHistry',
        ),
        migrations.DeleteModel(
            name='ClickHistryByUser',
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.DeleteModel(
            name='ControlWeb',
        ),
        migrations.DeleteModel(
            name='EmailSeenDB',
        ),
        migrations.DeleteModel(
            name='ExtraImageDB',
        ),
        migrations.DeleteModel(
            name='FreeTrialRequest',
        ),
        migrations.DeleteModel(
            name='FreeTrialUnderReview',
        ),
        migrations.DeleteModel(
            name='FreeTrialUser',
        ),
        migrations.DeleteModel(
            name='InternalVisit',
        ),
        migrations.DeleteModel(
            name='InternUserDetails',
        ),
        migrations.DeleteModel(
            name='OpenViaEmail',
        ),
        migrations.DeleteModel(
            name='OrderList',
        ),
        migrations.DeleteModel(
            name='PerDayOrderPerUser',
        ),
        migrations.DeleteModel(
            name='RegistationFormDB',
        ),
        migrations.DeleteModel(
            name='SubscribeList',
        ),
        migrations.DeleteModel(
            name='TransectionHistory',
        ),
        migrations.DeleteModel(
            name='UnsubscribeList',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
        migrations.DeleteModel(
            name='WhyUsDB',
        ),
    ]
